# Generated by Django 3.2 on 2021-04-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
