# Generated by Django 3.2 on 2021-04-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_business_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.URLField(default='default.jpg'),
        ),
    ]
