# Generated by Django 3.2 on 2021-04-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_hood_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='image',
            field=models.URLField(default='default.jpg'),
        ),
    ]
