# Generated by Django 3.2 on 2021-04-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210411_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='image',
            field=models.URLField(default='https://sharingtheglobe.files.wordpress.com/2012/02/dsc_0290.jpg'),
        ),
    ]
