# Generated by Django 3.2 on 2021-04-12 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210413_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoods', to='main.profile'),
        ),
    ]
